version: "3.8"

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=testos
      - POSTGRES_PASSWORD=bradr
    ports:
      - '7779:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: