version: "3.8"

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=hamza
      - POSTGRES_PASSWORD=password
    ports:
      - '7779:5432'
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
  app:
    ports:
      - 3000:3000
    build:
      context: ./
      dockerfile: ./Dockerfile
    links:
      - postgres
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

# volumes:
#   pgdata: